name: travel_atvisor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  cupertino_icons: ^1.0.2
  firebase_storage: ^10.2.6
  image_picker: 0.7.4
  image_cropper: ^1.4.1
  google_sign_in: ^5.2.3
  syncfusion_flutter_datepicker: ^19.4.52
  cloud_functions: ^3.2.7
  uuid: 3.0.6
  carousel_slider: 4.0.0
  url_launcher: 6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mountains.jpg
    - assets/empire.jpg
    - assets/ph_profile.png
