// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARhKY_B-Cxt3aCCdaOcYLvjMOUnPYQe2E',
    appId: '1:773474425139:android:db62073b943a243cf34646',
    messagingSenderId: '773474425139',
    projectId: 'travelatvisor',
    storageBucket: 'travelatvisor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVrbNEXeCyz0xYjmXteEpKdX3r_IfCYBE',
    appId: '1:773474425139:ios:032a710eef303154f34646',
    messagingSenderId: '773474425139',
    projectId: 'travelatvisor',
    storageBucket: 'travelatvisor.appspot.com',
    iosClientId: '773474425139-9ik9q0s1rgpluhr0php8d2gd3qs88mag.apps.googleusercontent.com',
    iosBundleId: 'com.travelatvisor.application',
  );
}
